name: Build and Push Docker Image and Helm Chart

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Set up Yarn
        run: |
          corepack enable
          yarn set version stable
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
  
  helm-chart:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: Setup Chart Version
        id: chart_version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"
          else
            VERSION="0.1.0-$(date +'%Y%m%d%H%M%S')"
          fi
          echo "Using chart version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Update Chart Version
        run: |
          sed -i "s/^version: .*$/version: ${{ env.VERSION }}/" charts/skill-wanderer/Chart.yaml
          sed -i "s/^appVersion: .*$/appVersion: ${{ env.VERSION }}/" charts/skill-wanderer/Chart.yaml
      
      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package charts/skill-wanderer --destination .cr-release-packages
      
      - name: Setup GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: false
          fetch-depth: 0
          clean: false
        continue-on-error: true
      
      - name: Create gh-pages branch if it doesn't exist
        run: |
          if [ ! -d "gh-pages" ]; then
            mkdir -p gh-pages
            cd gh-pages
            git init
            git checkout -b gh-pages
            git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            touch index.html
            echo "<html><body><h1>Helm Chart Repository</h1></body></html>" > index.html
            git add index.html
            git commit -m "Initial gh-pages commit"
            git push -u origin gh-pages
            cd ..
          fi
      
      - name: Update Helm Repository
        run: |
          mkdir -p gh-pages/charts
          cp .cr-release-packages/*.tgz gh-pages/charts/
          cd gh-pages
          if [ -f "index.yaml" ]; then
            helm repo index --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/charts --merge index.yaml .
          else
            helm repo index --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/charts .
          fi
          git add .
          git commit -m "Update Helm chart repository" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
      
      - name: Output Helm Repository Info
        run: |
          echo "::notice::Helm repository available at https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo "::notice::Add the repository to Helm with: helm repo add ${{ github.event.repository.name }} https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"